const BookmarksActionTypes = {
  ACTIVE_CATEGORY: 'ACTIVE_CATEGORY',
  ROMOVE_ACTIVE_BOOKMARK: 'ROMOVE_ACTIVE_BOOKMARK',
  GET_BOOKMARKS_START: 'GET_BOOKMARKS_START',
  GET_BOOKMARKS_SUCCESS: 'GET_BOOKMARKS_SUCCESS',
  GET_BOOKMARKS_FAILURE: 'GET_BOOKMARKS_FAILURE',
  ADD_BOOKMARK_START: 'ADD_BOOKMARK_START',
  ADD_BOOKMARK_SUCCESS: 'ADD_BOOKMARK_SUCCESS',
  ADD_BOOKMARK_FAILURE: 'ADD_BOOKMARK_FAILURE',
  DELETE_BOOKMARK_START: 'DELETE_BOOKMARK_START',
  DELETE_BOOKMARK_SUCCESS: 'DELETE_BOOKMARK_SUCCESS',
  DELETE_BOOKMARK_FAILURE: 'DELETE_BOOKMARK_FAILURE',
}

export default BookmarksActionTypes;