const bookmarks = {
  byId: {
    "bookmark1": {
      id: 'bookmark1',
      title: 'Oose ebook - Google Drive',
      url: 'https://drive.google.com/drive/u/0/folders/180AaaaOtOIodroEG4dzGYILeoq9sQ14N',
      tags: ['drive', 'book'],
      categoryId: 'category1',
    },
    "bookmark2": {
      id: 'bookmark2',
      title: 'SE A1 G3 - Google Drive',
      url: 'https://drive.google.com/drive/u/6/folders/17Fz4tZyrWMQEVQn2mrYHDxHWiup4NGgK',
      tags: ['drive', 'lab'],
      categoryId: 'category1',
    },
    "bookmark3": {
      id: 'bookmark3',
      title: 'A free online course - Elements of AI',
      url: 'https://course.elementsofai.com/',
      tags: ['ml', 'course', 'ai'],
      categoryId: 'category2',
    },
    "bookmark4": {
      id: 'bookmark4',
      title: 'UCI Machine Learning Repository: Data Sets',
      url: 'https://archive.ics.uci.edu/ml/datasets.php?format=&task=&att=&area=&numAtt=&numIns=&type=&sort=dateDown&view=table',
      tags: ['data sets', 'data', 'ml'],
      categoryId: 'category2',
    },
    "bookmark5": {
      id: 'bookmark5',
      title: 'Sci-Hub | Twitter-based Polarised Embeddings for Abusive Language Detection.',
      url: 'https://sci-hub.tw/10.1109/aciiw.2019.8925049',
      tags: ['ml', 'journal'],
      categoryId: 'category2',
    },
    "bookmark6": {
      id: 'bookmark6',
      title: 'Solve Algorithms | HackerRank',
      url: 'https://www.hackerrank.com/domains/algorithms',
      tags: ['algorithms', 'coding'],
      categoryId: 'category3',
    },
    "bookmark7": {
      id: 'bookmark7',
      title: 'Introduction to Engineering Economics',
      url: 'https://www.slideshare.net/PrabuU2/introduction-to-engineering-economics',
      tags: ['economics', 'article'],
      categoryId: 'category4',
    },
    "bookmark8": {
      id: 'bookmark8',
      title: 'We have given a language a^n b^n ,n ≥ 0, we have to check whether this language is regular or not?',
      url: 'https://classroom.google.com/u/6/c/MTI1ODc2NjE2MDQ1/sa/MTI1ODc2NjE2MDg3/details',
      tags: ['qns', 'classroom', 'assignment'],
      categoryId: 'category5',
    },
    "bookmark9": {
      id: 'bookmark9',
      title: 'Theory of Computation & Automata Theory - YouTube',
      url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRgp46KUv4ZY69yXmpwKOIev',
      tags: ['video', 'tutorial'],
      categoryId: 'category5',
    },
    "bookmark10": {
      id: 'bookmark10',
      title: 'Resume Manager | T&P DTU',
      url: 'http://tnp.dtu.ac.in/rm_2016-17/intern/intern_login',
      tags: ['intern', 'test'],
      categoryId: 'category7',
    },
    "bookmark11": {
      id: 'bookmark11',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category8',
    },
    "bookmark12": {
      id: 'bookmark12',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category8',
    },
    "bookmark13": {
      id: 'bookmark13',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category8',
    },
    "bookmark14": {
      id: 'bookmark14',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category9',
    },
    "bookmark15": {
      id: 'bookmark15',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category19',
    },
    "bookmark16": {
      id: 'bookmark16',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category9',
    },
    "bookmark17": {
      id: 'bookmark17',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category10',
    },
    "bookmark18": {
      id: 'bookmark18',
      title: '',
      url: '',
      tags: [''],
      category: 'category10',
    },
    "bookmark19": {
      id: 'bookmark19',
      title: '',
      url: '',
      tags: [''],
      categoryId: 'category10',
    },
    "bookmark20": {
      id: 'bookmark20',
      title: 'Getting Started – React',
      url: 'https://reactjs.org/docs/getting-started.html',
      tags: ['react', 'docs'],
      categoryId: 'category11',
    },
    "bookmark21": {
      id: 'bookmark21',
      title: 'Getting Started with Redux | Redux',
      url: 'https://redux.js.org/introduction/getting-started',
      tags: ['react', 'redux'],
      categoryId: 'category11',
    },
    "bookmark22": {
      id: 'bookmark22',
      title: 'React Router: Declarative Routing for React.js',
      url: 'https://reactrouter.com/web/guides/quick-start',
      tags: ['react', 'react-router'],
      categoryId: 'category11',
    },
    "bookmark23": {
      id: 'bookmark23',
      title: 'Web Developer Monthly 💻🚀 August 2020 | Zero To Mastery',
      url: 'https://zerotomastery.io/blog/web-developer-monthly-august-2020',
      tags: ['web', 'montly', 'blog'],
      categoryId: 'category11',
    },
    "bookmark24": {
      id: 'bookmark24',
      title: 'Node Weekly Issue 354: September 3, 2020',
      url: 'https://nodeweekly.com/issues/354',
      tags: ['node', 'blog'],
      categoryId: 'category12',
    },
    "bookmark25": {
      id: 'bookmark25',
      title: 'Express - Node.js web application framework',
      url: 'https://expressjs.com/',
      tags: ['node', 'express', 'docs'],
      categoryId: 'category12',
    },
    "bookmark26": {
      id: 'bookmark26',
      title: 'Animate.css',
      url: 'https://animate.style/',
      tags: ['css', 'animation'],
      categoryId: 'category13',
    },
    "bookmark27": {
      id: 'bookmark27',
      title: 'Flexbox Froggy - A game for learning CSS flexbox',
      url: 'http://flexboxfroggy.com/',
      tags: ['css', 'flex', 'flex box', 'game'],
      categoryId: 'category13',
    },
    "bookmark28": {
      id: 'bookmark28',
      title: 'Grid Garden - A game for learning CSS grid',
      url: 'https://cssgridgarden.com/',
      tags: ['css', 'grid', 'game'],
      category: 'category13',
    },
    "bookmark29": {
      id: 'bookmark29',
      title: 'CSS Transitions and Transforms for Beginners',
      url: 'https://thoughtbot.com/blog/transitions-and-transforms',
      tags: ['css', 'transition', 'transform'],
      categoryId: 'category13',
    },
    "bookmark30": {
      id: 'bookmark30',
      title: 'Introduction · Bootstrap',
      url: 'https://getbootstrap.com/docs/4.0/getting-started/introduction/',
      tags: ['css', 'bootstrap'],
      categoryId: 'category14',
    },
    "bookmark31": {
      id: 'bookmark31',
      title: 'Material-UI: A popular React UI framework',
      url: 'https://material-ui.com/',
      tags: ['css', 'material'],
      categoryId: 'category14',
    },
    "bookmark32": {
      id: 'bookmark32',
      title: 'The Modern JavaScript Tutorial',
      url: 'https://javascript.info/',
      tags: ['javascript', 'js'],
      categoryId: 'category15',
    },
    "bookmark33": {
      id: 'bookmark33',
      title: '1loc | Favorite JavaScript single line of code',
      url: '1loc | Favorite JavaScript single line of code',
      tags: ['js', 'javascript', 'one line'],
      categoryId: 'category15',
    },
    "bookmark34": {
      id: 'bookmark34',
      title: 'Introduction | Socket.IO',
      url: 'https://socket.io/docs/',
      tags: ['sockit', 'docs', 'js'],
      categoryId: 'category15',
    },
    "bookmark35": {
      id: 'bookmark35',
      title: 'Community Coding Challenges | Zero To Mastery',
      url: 'https://zerotomastery.io/community/coding-challenges/',
      tags: ['coding', 'challenge', 'js', 'javascript'],
      categoryId: 'category15',
    },
    "bookmark36": {
      id: 'bookmark36',
      title: 'javascript-questions: A long list of (advanced) JavaScript questions, and their explanations',
      url: 'https://github.com/lydiahallie/javascript-questions',
      tags: ['qns', 'js', 'javascript'],
      categoryId: 'category15',
    },
  },
  allIds: [
    'bookmark1',
    'bookmark2',
    'bookmark3',
    'bookmark4',
    'bookmark5',
    'bookmark6',
    'bookmark7',
    'bookmark8',
    'bookmark9',
    'bookmark10',
    'bookmark11',
    'bookmark12',
    'bookmark13',
    'bookmark14',
    'bookmark15',
    'bookmark16',
    'bookmark17',
    'bookmark18',
    'bookmark19',
    'bookmark20',
    'bookmark21',
    'bookmark22',
    'bookmark23',
    'bookmark24',
    'bookmark25',
    'bookmark26',
    'bookmark27',
    'bookmark28',
    'bookmark29',
    'bookmark30',
    'bookmark31',
    'bookmark32',
    'bookmark33',
    'bookmark34',
    'bookmark35',
    'bookmark36',
  ]
}

export default bookmarks;