
const UserActionTypes = {
  "LOGIN_START": 'LOGIN_START',
  "LOGIN_SUCCESS": 'LOGIN_SUCCESS',
  "LOGIN_FAILURE": 'LOGIN_FAILURE',
  "SIGNUP_START": "SIGNUP_START",
  "SIGNUP_SUCCESS": "SIGNUP_SUCCESS",
  "SIGNUP_FAILURE": "SIGNUP_FAILURE",
  "CHECK_LOGIN": "CHECK_LOGIN",
  "LOGOUT": 'LOGOUT',
  USERS_LIST_START: 'USERS_LIST_START',
  USERS_LIST_SUCCESS: 'USERS_LIST_SUCCESS',
  USERS_LIST_FAILURE: 'USERS_LIST_FAILURE',
  USER_DETAILS_START: 'USER_DETAILS_START',
  USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
  USER_DETAILS_FAILURE: 'USER_DETAILS_FAILURE',
  CHANGE_PASSWORD_START: 'CHANGE_PASSWORD_START',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',
  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
}

export default UserActionTypes;