const TabActionTypes = {
  ADD_TAB_START: 'ADD_TAB_START',
  ADD_TAB_SUCCESS: 'ADD_TAB_SUCCESS',
  ADD_TAB_FAILURE: 'ADD_TAB_FAILURE',
  DELETE_TAB_START: 'DELETE_TAB_START',
  DELETE_TAB_SUCCESS: 'DELETE_TAB_SUCCESS',
  DELETE_TAB_FAILURE: 'DELETE_TAB_FAILURE',
  FETCH_TABS_START: 'FETCH_TABS_START',
  FETCH_TABS_SUCCESS: 'FETCH_TABS_SUCCESS',
  FETCH_TABS_FAILURE: 'FETCH_TABS_FAILURE',
}


export default TabActionTypes;